"""VS Code theme JSON specification."""

import json
from types import SimpleNamespace

_BASE_COLORS = {
    "brightYellow": "#fffac2",
    "brightMint": "#5DE4c7",
    "lowerMint": "#5fb3a1",
    "bluishGreen": "#42675A",
    "lowerBlue": "#89ddff",
    "lightBlue": "#ADD7FF",
    "desaturatedBlue": "#91B4D5",
    "bluishGrayBrighter": "#7390AA",
    "hotRed": "#d0679d",
    "pink": "#f087bd",
    "gray": "#a6accd",
    "darkerGray": "#767c9d",
    "bluishGray": "#506477",
    "focus": "#303340",
    "bg": "#1b1e28",
    "offWhite": "#e4f0fb",
    "highlight": "#717cb425",
    "selection": "#717cb460",
    "white": "#ffffff",
    "black": "#000000",
    "transparent": "#00000000",
    "purple": "#a590ff",
    "orange": "#edb469",
    "darkBg": "#1a1c25",
}

_BASE_STYLES = {"fontStyle": "italic"}

base = {"colors": dict(_BASE_COLORS), "styles": dict(_BASE_STYLES)}

storm = {
    "colors": {
        **_BASE_COLORS,
        "darkerGray": "#868cad",
        "bluishGray": "#607487",
        "focus": "#404350",
        "bg": "#252b37",
        "highlight": "#818cc425",
        "selection": "#818cc460",
        "black": "#101010",
        "darkBg": "#222531",
    },
    "styles": dict(_BASE_STYLES),
}


def schema(theme: dict) -> str:
    colors = SimpleNamespace(**theme["colors"])
    styles = SimpleNamespace(**theme["styles"])
    return json.dumps(_build_schema(colors, styles), indent=2)


def _build_schema(colors: SimpleNamespace, styles: SimpleNamespace) -> dict:
    return {
        "name": "poimandres dark theme (python)",
        "type": "dark",
        "colors": {
            # Bracket highlighting (new)
            "editorBracketHighlight.foreground1": "#e0af68",  # "#c49a5a"
            "editorBracketHighlight.foreground2": "#9ECE6A",  # "#80a856"
            "editorBracketHighlight.foreground3": "#2AC3DE",  # "#25aac2"
            "editorBracketHighlight.foreground4": "#BB9AF7",  # "#9a7ecc"
            "editorBracketHighlight.foreground5": "#7DCFFF",  # "#68b3de"
            "editorBracketHighlight.foreground6": "#7AA2F7",  # "#698cd6"
            "editorBracketHighlight.unexpectedBracket.foreground": "#db4b4b",
            "editorBracketPairGuide.activeBackground1": "#c49a5a",
            "editorBracketPairGuide.activeBackground2": "#80a856",
            "editorBracketPairGuide.activeBackground3": "#25aac2",
            "editorBracketPairGuide.activeBackground4": "#9a7ecc",
            "editorBracketPairGuide.activeBackground5": "#68b3de",
            "editorBracketPairGuide.activeBackground6": "#698cd6",
            # From before
            "activityBar.background": f"{colors.bg}",
            "activityBar.foreground": f"{colors.gray}",
            "activityBarBadge.background": f"{colors.lightBlue}",
            "activityBarBadge.foreground": f"{colors.bg}",
            "badge.background": f"{colors.focus}",
            "badge.foreground": f"{colors.offWhite}",
            "button.background": f"{colors.focus}",
            "diffEditor.insertedLineBackground": f"#5de4a025",
            "diffEditor.removedLineBackground": f"{colors.hotRed}40",
            "diffEditor.insertedTextBackground": f"{colors.bluishGray}15",
            "diffEditor.removedTextBackground": f"{colors.hotRed}20",
            "dropdown.background": f"{colors.bg}",
            "dropdown.border": f"{colors.white}10",
            "editor.background": f"{colors.bg}",
            "editor.findMatchBackground": f"{colors.lightBlue}40",
            "editor.findMatchBorder": f"{colors.lightBlue}",
            "editor.findMatchHighlightBackground": f"{colors.lightBlue}40",
            "editor.foreground": f"{colors.gray}",
            "editor.lineHighlightBackground": f"{colors.highlight}",
            "editor.inactiveLineHighlightBackground": f"{colors.lightBlue}10",
            "editor.selectionBackground": f"{colors.lightBlue}40",
            "editor.selectionHighlightBackground": f"{colors.lightBlue}10",
            "editor.inactiveSelectionBackground": f"{colors.lightBlue}40",
            "editor.wordHighlightBackground": f"{colors.lightBlue}10",
            "editor.wordHighlightStrongBackground": f"{colors.lightBlue}10",
            "editorBracketMatch.border": f"{colors.offWhite}60",
            "editorCursor.foreground": f"{colors.gray}",
            "editorGroup.border": f"{colors.black}30",
            "editorGroupHeader.tabsBackground": f"{colors.bg}",
            "editorHoverWidget.background": f"{colors.bg}",
            "editorHoverWidget.border": f"{colors.white}10",
            "editorIndentGuide.background1": f"{colors.focus}",
            "editorLineNumber.foreground": f"{colors.darkerGray}6a",
            "editorLink.activeForeground": f"{colors.lightBlue}",
            "editorSuggestWidget.background": f"{colors.bg}",
            "editorSuggestWidget.border": f"{colors.white}10",
            "editorSuggestWidget.foreground": f"{colors.gray}",
            "editorSuggestWidget.highlightForeground": f"{colors.brightMint}",
            "editorSuggestWidget.selectedBackground": f"{colors.black}50",
            "editorWidget.background": f"{colors.bg}",
            "editor.findRangeHighlightBackground": f"{colors.lightBlue}40",
            "editor.focusedStackFrameHighlightBackground": "#7abd7a4d",
            "editor.foldBackground": "#717cb40b",
            "editor.hoverHighlightBackground": "#264f7840",
            "editor.inactiveSelectionBackground": f"{colors.highlight}",
            "editor.linkedEditingBackground": f"{colors.hotRed}4d",
            "editor.rangeHighlightBackground": f"{colors.white}0b",
            "editor.snippetFinalTabstopHighlightBorder": "#525252",
            "editor.snippetTabstopHighlightBackground": "#7c7c7c4d",
            "editor.stackFrameHighlightBackground": "#ffff0033",
            "editor.symbolHighlightBackground": f"{colors.lowerBlue}60",
            "editorBracketMatch.background": f"{colors.transparent}",
            "editorCodeLens.foreground": f"{colors.gray}",
            "editorError.foreground": f"{colors.hotRed}",
            "editorGroup.dropBackground": f"{colors.bluishGrayBrighter}80",
            "editorGroupHeader.noTabsBackground": f"{colors.bg}",
            "editorGutter.background": f"{colors.bg}",
            "editorGutter.commentRangeForeground": f"{colors.gray}",
            "editorGutter.foldingControlForeground": f"{colors.gray}",
            "editorGutter.addedBackground": f"{colors.lowerMint}a0",
            "editorGutter.deletedBackground": f"{colors.hotRed}a0",
            "editorGutter.modifiedBackground": f"{colors.lightBlue}70",
            "editorHint.foreground": f"{colors.bluishGrayBrighter}b3",
            "editorHoverWidget.foreground": f"{colors.gray}",
            "editorHoverWidget.statusBarBackground": "#202430",
            "editorIndentGuide.activeBackground": "#e3e4e229",
            "editorInfo.foreground": f"{colors.lightBlue}",
            "editorInlineHint.background": f"{colors.gray}",
            "editorInlineHint.foreground": f"{colors.bg}",
            "editorLightBulb.foreground": f"{colors.brightYellow}",
            "editorLightBulbAutoFix.foreground": f"{colors.lightBlue}",
            "editorLineNumber.activeForeground": f"{colors.gray}",
            "editorMarkerNavigation.background": "#2d2d30",
            "editorMarkerNavigationError.background": f"{colors.hotRed}",
            "editorMarkerNavigationInfo.background": f"{colors.lightBlue}",
            "editorMarkerNavigationWarning.background": f"{colors.brightYellow}",
            "editorOverviewRuler.addedForeground": f"{colors.lowerMint}99",
            "editorOverviewRuler.border": f"{colors.transparent}",
            "editorOverviewRuler.bracketMatchForeground": "#a0a0a0",
            "editorOverviewRuler.commonContentForeground": f"{colors.gray}66",
            "editorOverviewRuler.currentContentForeground": f"{colors.lowerMint}80",
            "editorOverviewRuler.deletedForeground": f"{colors.hotRed}99",
            "editorOverviewRuler.errorForeground": f"{colors.hotRed}b3",
            "editorOverviewRuler.findMatchForeground": f"{colors.offWhite}20",
            "editorOverviewRuler.incomingContentForeground": f"{colors.lowerBlue}80",
            "editorOverviewRuler.infoForeground": f"{colors.lightBlue}",
            "editorOverviewRuler.modifiedForeground": f"{colors.lowerBlue}99",
            "editorOverviewRuler.rangeHighlightForeground": f"{colors.lowerBlue}99",
            "editorOverviewRuler.selectionHighlightForeground": "#a0a0a0cc",
            "editorOverviewRuler.warningForeground": f"{colors.brightYellow}",
            "editorOverviewRuler.wordHighlightForeground": "#a0a0a0cc",
            "editorOverviewRuler.wordHighlightStrongForeground": f"{colors.lowerBlue}cc",
            "editorPane.background": f"{colors.bg}",
            "editorRuler.foreground": f"{colors.offWhite}10",
            "editorUnnecessaryCode.opacity": f"{colors.white}65",
            "editorWarning.foreground": f"{colors.brightYellow}",
            "editorWhitespace.foreground": f"{colors.focus}",
            "editorWidget.border": f"{colors.gray}",
            "editorWidget.foreground": f"{colors.gray}",
            "extensionButton.prominentBackground": f"{colors.focus}90",
            "extensionButton.prominentHoverBackground": f"{colors.focus}",
            "focusBorder": f"{colors.transparent}",
            "input.background": f"{colors.white}05",
            "input.border": f"{colors.white}10",
            "input.foreground": f"{colors.offWhite}",
            "input.placeholderForeground": f"{colors.gray}60",
            "inputValidation.errorBorder": f"{colors.hotRed}",
            "inputValidation.errorForeground": f"{colors.hotRed}",
            "inputValidation.infoBorder": f"{colors.lowerBlue}",
            "inputValidation.warningBorder": f"{colors.brightYellow}",
            "notifications.background": f"{colors.bg}",
            "notifications.foreground": f"{colors.offWhite}",
            "panel.border": f"{colors.black}30",
            "panelTitle.activeForeground": f"{colors.gray}",
            "peekView.border": f"{colors.black}30",
            "peekViewEditor.background": f"{colors.gray}05",
            "peekViewEditorGutter.background": f"{colors.gray}05",
            "peekViewResult.background": f"{colors.gray}05",
            "peekViewTitle.background": f"{colors.gray}05",
            "peekViewTitleDescription.foreground": f"{colors.gray}60",
            "scrollbar.shadow": f"{colors.transparent}",
            "scrollbarSlider.activeBackground": f"{colors.gray}b0",
            "scrollbarSlider.background": f"{colors.gray}30",
            "scrollbarSlider.hoverBackground": f"{colors.gray}70",
            "selection.background": f"{colors.gray}",
            "sideBar.background": f"{colors.bg}",
            "sideBar.foreground": f"{colors.darkerGray}",
            "sideBarSectionHeader.background": f"{colors.bg}",
            "sideBarTitle.foreground": f"{colors.gray}",
            "statusBar.background": f"{colors.bg}",
            "statusBar.foreground": f"{colors.gray}",
            "statusBar.noFolderBackground": f"{colors.bg}",
            "tab.activeBackground": f"{colors.focus}70",
            "tab.activeForeground": f"{colors.offWhite}",
            "tab.activeBorder": f"{colors.brightMint}",
            "tab.border": f"{colors.transparent}",
            "tab.inactiveBackground": f"{colors.bg}",
            "tab.inactiveForeground": f"{colors.darkerGray}",
            "tab.unfocusedActiveForeground": f"{colors.darkerGray}a0",
            "tab.unfocusedActiveBorder": f"{colors.darkerGray}a0",
            "tab.activeModifiedBorder": f"{colors.lightBlue}",
            "tab.inactiveModifiedBorder": f"{colors.lightBlue}80",
            "tab.lastPinnedBorder": f"{colors.transparent}",
            "tab.unfocusedActiveBackground": f"{colors.bg}",
            "tab.unfocusedActiveModifiedBorder": f"{colors.lightBlue}40",
            "tab.unfocusedInactiveBackground": f"{colors.bg}",
            "tab.unfocusedInactiveForeground": f"{colors.darkerGray}70",
            "tab.unfocusedInactiveModifiedBorder": f"{colors.lightBlue}40",
            "terminal.ansiBlack": f"{colors.bg}",
            "terminal.ansiBlue": f"{colors.lowerBlue}",
            "terminal.ansiBrightBlack": f"{colors.gray}",
            "terminal.ansiBrightBlue": f"{colors.lightBlue}",
            "terminal.ansiBrightCyan": f"{colors.lightBlue}",
            "terminal.ansiBrightGreen": f"{colors.brightMint}",
            "terminal.ansiBrightMagenta": f"{colors.pink}",
            "terminal.ansiBrightRed": f"{colors.hotRed}",
            "terminal.ansiBrightWhite": f"{colors.white}",
            "terminal.ansiBrightYellow": f"{colors.brightYellow}",
            "terminal.ansiCyan": f"{colors.lowerBlue}",
            "terminal.ansiGreen": f"{colors.brightMint}",
            "terminal.ansiMagenta": f"{colors.pink}",
            "terminal.ansiRed": f"{colors.hotRed}",
            "terminal.ansiWhite": f"{colors.white}",
            "terminal.ansiYellow": f"{colors.brightYellow}",
            "textLink.activeForeground": f"{colors.lightBlue}",
            "textLink.foreground": f"{colors.lightBlue}",
            "titleBar.activeBackground": f"{colors.bg}",
            "titleBar.activeForeground": f"{colors.gray}",
            "titleBar.inactiveBackground": f"{colors.bg}",
            "titleBar.inactiveForeground": f"{colors.darkerGray}",
            "tree.indentGuidesStroke": f"{colors.focus}",
            "widget.shadow": f"{colors.black}30",
            "activityBar.activeBorder": f"{colors.gray}",
            "activityBar.dropBorder": f"{colors.gray}",
            "activityBar.inactiveForeground": f"{colors.gray}66",
            "breadcrumb.activeSelectionForeground": f"{colors.offWhite}",
            "breadcrumb.background": f"{colors.transparent}",
            "breadcrumb.focusForeground": f"{colors.offWhite}",
            "breadcrumb.foreground": f"{colors.darkerGray}cc",
            "breadcrumbPicker.background": f"{colors.bg}",
            "button.foreground": f"{colors.white}",
            "button.hoverBackground": f"{colors.bluishGray}50",
            "button.secondaryBackground": f"{colors.gray}",
            "button.secondaryForeground": f"{colors.white}",
            "button.secondaryHoverBackground": f"{colors.gray}",
            "charts.blue": f"{colors.lightBlue}",
            "charts.foreground": f"{colors.gray}",
            "charts.green": f"{colors.brightMint}",
            "charts.lines": f"{colors.gray}80",
            "charts.orange": f"{colors.lowerBlue}",
            "charts.purple": f"{colors.pink}",
            "charts.red": f"{colors.hotRed}",
            "charts.yellow": f"{colors.brightYellow}",
            "checkbox.background": f"{colors.bg}",
            "checkbox.border": f"{colors.white}10",
            "checkbox.foreground": f"{colors.offWhite}",
            "debugConsole.errorForeground": f"{colors.hotRed}",
            "debugConsole.infoForeground": f"{colors.lightBlue}",
            "debugConsole.sourceForeground": f"{colors.gray}",
            "debugConsole.warningForeground": f"{colors.brightYellow}",
            "debugConsoleInputIcon.foreground": f"{colors.gray}",
            "debugExceptionWidget.background": f"{colors.hotRed}",
            "debugExceptionWidget.border": f"{colors.hotRed}",
            "debugIcon.breakpointCurrentStackframeForeground": f"{colors.brightYellow}",
            "debugIcon.breakpointDisabledForeground": f"{colors.bluishGrayBrighter}",
            "debugIcon.breakpointForeground": f"{colors.hotRed}",
            "debugIcon.breakpointStackframeForeground": f"{colors.lowerMint}",
            "debugIcon.breakpointUnverifiedForeground": f"{colors.bluishGrayBrighter}",
            "debugIcon.continueForeground": f"{colors.lightBlue}",
            "debugIcon.disconnectForeground": f"{colors.hotRed}",
            "debugIcon.pauseForeground": f"{colors.lightBlue}",
            "debugIcon.restartForeground": f"{colors.lowerMint}",
            "debugIcon.startForeground": f"{colors.lowerMint}",
            "debugIcon.stepBackForeground": f"{colors.lightBlue}",
            "debugIcon.stepIntoForeground": f"{colors.lightBlue}",
            "debugIcon.stepOutForeground": f"{colors.lightBlue}",
            "debugIcon.stepOverForeground": f"{colors.lightBlue}",
            "debugIcon.stopForeground": f"{colors.hotRed}",
            "debugTokenExpression.boolean": f"{colors.lowerBlue}",
            "debugTokenExpression.error": f"{colors.hotRed}",
            "debugTokenExpression.name": f"{colors.offWhite}",
            "debugTokenExpression.number": f"{colors.lowerMint}",
            "debugTokenExpression.string": f"{colors.lowerBlue}",
            "debugTokenExpression.value": f"{colors.gray}99",
            "debugToolBar.background": f"{colors.focus}",
            "debugView.exceptionLabelBackground": f"{colors.hotRed}",
            "debugView.exceptionLabelForeground": f"{colors.offWhite}",
            "debugView.stateLabelBackground": f"{colors.focus}",
            "debugView.stateLabelForeground": f"{colors.gray}",
            "debugView.valueChangedHighlight": f"{colors.lowerBlue}",
            "descriptionForeground": f"{colors.gray}b3",
            "diffEditor.diagonalFill": f"{colors.gray}33",
            "dropdown.foreground": f"{colors.offWhite}",
            "errorForeground": f"{colors.hotRed}",
            "extensionBadge.remoteBackground": f"{colors.focus}",
            "extensionBadge.remoteForeground": f"{colors.offWhite}",
            "extensionButton.prominentForeground": f"{colors.white}",
            "extensionIcon.starForeground": f"{colors.brightYellow}",
            "foreground": f"{colors.gray}",
            "gitDecoration.addedResourceForeground": f"{colors.lowerMint}",
            "gitDecoration.conflictingResourceForeground": f"{colors.hotRed}",
            "gitDecoration.deletedResourceForeground": f"{colors.hotRed}",
            "gitDecoration.ignoredResourceForeground": f"{colors.darkerGray}70",
            "gitDecoration.modifiedResourceForeground": f"{colors.lightBlue}",
            "gitDecoration.renamedResourceForeground": f"{colors.brightMint}",
            "gitDecoration.stageDeletedResourceForeground": f"{colors.hotRed}",
            "gitDecoration.stageModifiedResourceForeground": f"{colors.lightBlue}",
            "gitDecoration.submoduleResourceForeground": f"{colors.lowerBlue}",
            "gitDecoration.untrackedResourceForeground": f"{colors.brightMint}",
            "icon.foreground": f"{colors.gray}",
            "imagePreview.border": f"{colors.focus}",
            "inputOption.activeBackground": f"{colors.selection}",
            "inputOption.activeBorder": f"{colors.transparent}",
            "inputOption.activeForeground": f"{colors.white}",
            "inputValidation.errorBackground": f"{colors.bg}",
            "inputValidation.infoBackground": f"{colors.bluishGray}",
            "inputValidation.warningBackground": f"{colors.bluishGray}",
            "list.deemphasizedForeground": f"{colors.darkerGray}",
            "list.dropBackground": f"{colors.bluishGray}",
            "list.filterMatchBackground": f"{colors.lowerBlue}60",
            "list.focusOutline": f"{colors.transparent}",
            "list.invalidItemForeground": f"{colors.brightYellow}",
            "list.warningForeground": f"{colors.brightYellow}",
            "listFilterWidget.background": f"{colors.focus}",
            "listFilterWidget.noMatchesOutline": f"{colors.hotRed}",
            "listFilterWidget.outline": f"{colors.transparent}",
            "list.activeSelectionBackground": f"{colors.focus}80",
            "list.activeSelectionForeground": f"{colors.offWhite}",
            "list.errorForeground": f"{colors.hotRed}",
            "list.focusBackground": f"{colors.focus}80",
            "list.focusForeground": f"{colors.gray}",
            "list.highlightForeground": f"{colors.lowerMint}",
            "list.hoverBackground": f"{colors.focus}80",
            "list.hoverForeground": f"{colors.offWhite}",
            "list.inactiveSelectionBackground": f"{colors.focus}80",
            "list.inactiveSelectionForeground": f"{colors.offWhite}",
            "menu.background": f"{colors.bg}",
            "menu.foreground": f"{colors.offWhite}",
            "menu.selectionBackground": f"{colors.focus}",
            "menu.selectionForeground": f"{colors.bluishGrayBrighter}",
            "menu.separatorBackground": f"{colors.darkerGray}",
            "menubar.selectionBackground": f"{colors.highlight}",
            "menubar.selectionForeground": f"{colors.gray}",
            "merge.commonContentBackground": f"{colors.gray}29",
            "merge.commonHeaderBackground": f"{colors.gray}66",
            "merge.currentContentBackground": f"{colors.lowerMint}33",
            "merge.currentHeaderBackground": f"{colors.lowerMint}80",
            "merge.incomingContentBackground": f"{colors.lowerBlue}33",
            "merge.incomingHeaderBackground": f"{colors.lowerBlue}80",
            "minimap.errorHighlight": f"{colors.hotRed}",
            "minimap.findMatchHighlight": f"{colors.lightBlue}",
            "minimap.selectionHighlight": f"{colors.offWhite}40",
            "minimap.warningHighlight": f"{colors.brightYellow}",
            "minimapGutter.addedBackground": f"{colors.lowerMint}80",
            "minimapGutter.deletedBackground": f"{colors.hotRed}80",
            "minimapGutter.modifiedBackground": f"{colors.lightBlue}80",
            "minimapSlider.activeBackground": f"{colors.gray}30",
            "minimapSlider.background": f"{colors.gray}20",
            "minimapSlider.hoverBackground": f"{colors.gray}30",
            "notebook.cellBorderColor": f"{colors.transparent}",
            "notebook.cellEditorBackground": f"{colors.darkBg}",
            "notebook.cellInsertionIndicator": f"{colors.transparent}",
            "notebook.cellStatusBarItemHoverBackground": f"{colors.white}26",
            "notebook.cellToolbarSeparator": f"{colors.focus}",
            "notebook.focusedCellBackground": f"{colors.darkerGray}18",
            "notebook.focusedCellBorder": f"{colors.lowerMint}a0",
            "notebook.focusedRowBorder": f"{colors.transparent}",
            "notebook.inactiveFocusedCellBorder": f"{colors.darkBg}",
            "notebook.outputContainerBackgroundColor": f"{colors.bg}",
            "notebook.outputContainerBorderColor": f"{colors.hotRed}",
            "notebook.rowHoverBackground": f"{colors.focus}00",
            "notebook.selectedCellBackground": f"{colors.focus}",
            "notebook.selectedCellBorder": f"{colors.bg}",
            "notebook.symbolHighlightBackground": f"{colors.white}0b",
            "notebookScrollbarSlider.activeBackground": f"{colors.gray}b0",
            "notebookScrollbarSlider.background": f"{colors.gray}30",
            "notebookScrollbarSlider.hoverBackground": f"{colors.gray}70",
            "notebookStatusErrorIcon.foreground": f"{colors.hotRed}",
            "notebookStatusRunningIcon.foreground": f"{colors.gray}",
            "notebookStatusSuccessIcon.foreground": f"{colors.lowerMint}",
            "notificationCenterHeader.background": f"{colors.focus}",
            "notificationLink.foreground": f"{colors.lightBlue}",
            "notifications.border": f"{colors.focus}",
            "notificationsErrorIcon.foreground": f"{colors.hotRed}",
            "notificationsInfoIcon.foreground": f"{colors.lightBlue}",
            "notificationsWarningIcon.foreground": f"{colors.brightYellow}",
            "panel.background": f"{colors.bg}",
            "panel.dropBorder": f"{colors.gray}",
            "panelSection.border": f"{colors.bg}",
            "panelSection.dropBackground": f"{colors.bluishGrayBrighter}80",
            "panelSectionHeader.background": f"{colors.focus}",
            "panelTitle.activeBorder": f"{colors.gray}",
            "panelTitle.inactiveForeground": f"{colors.gray}99",
            "peekViewEditor.matchHighlightBackground": f"{colors.focus}",
            "peekViewResult.fileForeground": f"{colors.white}",
            "peekViewResult.lineForeground": f"{colors.gray}",
            "peekViewResult.matchHighlightBackground": f"{colors.focus}",
            "peekViewResult.selectionBackground": f"{colors.highlight}",
            "peekViewResult.selectionForeground": f"{colors.white}",
            "peekViewTitleLabel.foreground": f"{colors.white}",
            "pickerGroup.border": f"{colors.gray}",
            "pickerGroup.foreground": f"{colors.lowerBlue}",
            "problemsErrorIcon.foreground": f"{colors.hotRed}",
            "problemsInfoIcon.foreground": f"{colors.lightBlue}",
            "problemsWarningIcon.foreground": f"{colors.brightYellow}",
            "progressBar.background": f"{colors.lowerBlue}",
            "quickInput.background": f"{colors.bg}",
            "quickInput.foreground": f"{colors.gray}",
            "quickInputList.focusBackground": f"{colors.gray}10",
            "quickInputTitle.background": f"{colors.white}1b",
            "sash.hoverBorder": f"{colors.transparent}",
            "scm.providerBorder": f"{colors.offWhite}10",
            "searchEditor.findMatchBackground": f"{colors.lightBlue}50",
            "searchEditor.textInputBorder": f"{colors.white}10",
            "settings.checkboxBackground": f"{colors.bg}",
            "settings.checkboxBorder": f"{colors.white}10",
            "settings.checkboxForeground": f"{colors.offWhite}",
            "settings.dropdownBackground": f"{colors.bg}",
            "settings.dropdownBorder": f"{colors.white}10",
            "settings.dropdownForeground": f"{colors.offWhite}",
            "settings.dropdownListBorder": f"{colors.offWhite}10",
            "settings.focusedRowBackground": f"{colors.transparent}",
            "settings.headerForeground": f"{colors.offWhite}",
            "settings.modifiedItemIndicator": f"{colors.lightBlue}",
            "settings.numberInputBackground": f"{colors.white}05",
            "settings.numberInputBorder": f"{colors.white}10",
            "settings.numberInputForeground": f"{colors.offWhite}",
            "settings.textInputBackground": f"{colors.white}05",
            "settings.textInputBorder": f"{colors.white}10",
            "settings.textInputForeground": f"{colors.offWhite}",
            "sideBar.dropBackground": f"{colors.bluishGrayBrighter}80",
            "sideBarSectionHeader.foreground": f"{colors.gray}",
            "statusBar.debuggingBackground": f"{colors.focus}",
            "statusBar.debuggingForeground": f"{colors.white}",
            "statusBar.noFolderForeground": f"{colors.gray}",
            "statusBarItem.activeBackground": f"{colors.white}2e",
            "statusBarItem.errorBackground": f"{colors.hotRed}",
            "statusBarItem.errorForeground": f"{colors.white}",
            "statusBarItem.hoverBackground": f"{colors.white}1f",
            "statusBarItem.prominentBackground": f"{colors.black}80",
            "statusBarItem.prominentForeground": f"{colors.gray}",
            "statusBarItem.prominentHoverBackground": f"{colors.black}4d",
            "statusBarItem.remoteBackground": f"{colors.focus}",
            "statusBarItem.remoteForeground": f"{colors.offWhite}",
            "symbolIcon.arrayForeground": f"{colors.gray}",
            "symbolIcon.booleanForeground": f"{colors.gray}",
            "symbolIcon.classForeground": f"{colors.brightYellow}",
            "symbolIcon.colorForeground": f"{colors.gray}",
            "symbolIcon.constantForeground": f"{colors.gray}",
            "symbolIcon.constructorForeground": f"{colors.pink}",
            "symbolIcon.enumeratorForeground": f"{colors.brightYellow}",
            "symbolIcon.enumeratorMemberForeground": f"{colors.lightBlue}",
            "symbolIcon.eventForeground": f"{colors.brightYellow}",
            "symbolIcon.fieldForeground": f"{colors.lightBlue}",
            "symbolIcon.fileForeground": f"{colors.gray}",
            "symbolIcon.folderForeground": f"{colors.gray}",
            "symbolIcon.functionForeground": f"{colors.pink}",
            "symbolIcon.interfaceForeground": f"{colors.lightBlue}",
            "symbolIcon.keyForeground": f"{colors.gray}",
            "symbolIcon.keywordForeground": f"{colors.gray}",
            "symbolIcon.methodForeground": f"{colors.pink}",
            "symbolIcon.moduleForeground": f"{colors.gray}",
            "symbolIcon.namespaceForeground": f"{colors.gray}",
            "symbolIcon.nullForeground": f"{colors.gray}",
            "symbolIcon.numberForeground": f"{colors.gray}",
            "symbolIcon.objectForeground": f"{colors.gray}",
            "symbolIcon.operatorForeground": f"{colors.gray}",
            "symbolIcon.packageForeground": f"{colors.gray}",
            "symbolIcon.propertyForeground": f"{colors.gray}",
            "symbolIcon.referenceForeground": f"{colors.gray}",
            "symbolIcon.snippetForeground": f"{colors.gray}",
            "symbolIcon.stringForeground": f"{colors.gray}",
            "symbolIcon.structForeground": f"{colors.gray}",
            "symbolIcon.textForeground": f"{colors.gray}",
            "symbolIcon.typeParameterForeground": f"{colors.gray}",
            "symbolIcon.unitForeground": f"{colors.gray}",
            "symbolIcon.variableForeground": f"{colors.lightBlue}",
            "terminal.border": f"{colors.transparent}",
            "terminal.foreground": f"{colors.gray}",
            "terminal.selectionBackground": f"{colors.highlight}",
            "terminalCommandDecoration.errorBackground": f"{colors.hotRed}",
            "terminalCommandDecoration.successBackground": f"{colors.brightMint}",
            "terminalCommandDecoration.defaultBackground": f"{colors.darkerGray}",
            "testing.iconErrored": f"{colors.hotRed}",
            "testing.iconFailed": f"{colors.hotRed}",
            "testing.iconPassed": f"{colors.brightMint}",
            "testing.iconQueued": f"{colors.brightYellow}",
            "testing.iconSkipped": f"{colors.bluishGrayBrighter}",
            "testing.iconUnset": f"{colors.bluishGrayBrighter}",
            "testing.message.error.decorationForeground": f"{colors.hotRed}",
            "testing.message.error.lineBackground": f"{colors.hotRed}33",
            "testing.message.hint.decorationForeground": f"{colors.bluishGrayBrighter}b3",
            "testing.message.info.decorationForeground": f"{colors.lightBlue}",
            "testing.message.info.lineBackground": f"{colors.lowerBlue}33",
            "testing.message.warning.decorationForeground": f"{colors.brightYellow}",
            "testing.message.warning.lineBackground": f"{colors.brightYellow}33",
            "testing.peekBorder": f"{colors.hotRed}",
            "testing.runAction": f"{colors.brightMint}",
            "textBlockQuote.background": f"{colors.bluishGrayBrighter}1a",
            "textBlockQuote.border": f"{colors.lowerBlue}80",
            "textCodeBlock.background": f"{colors.black}50",
            "textPreformat.foreground": f"{colors.offWhite}",
            "textSeparator.foreground": f"{colors.white}2e",
            "tree.tableColumnsBorder": f"{colors.gray}20",
            "welcomePage.progress.background": f"{colors.white}05",
            "welcomePage.progress.foreground": f"{colors.lowerMint}",
            "welcomePage.tileBackground": f"{colors.bg}",
            "welcomePage.tileHoverBackground": f"{colors.focus}",
        },
        "tokenColors": [
            {
                "scope": ["comment", "punctuation.definition.comment"],
                "settings": {
                    "foreground": f"{colors.darkerGray}B0",
                    "fontStyle": f"{styles.fontStyle}",
                },
            },
            {
                "scope": "meta.parameters comment.block",
                "settings": {
                    "foreground": f"{colors.gray}",
                    "fontStyle": f"{styles.fontStyle}",
                },
            },
            {
                "scope": [
                    "variable.other.constant.object",
                    "variable.other.readwrite.alias",
                    "meta.import variable.other.readwrite",
                ],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["variable.other", "support.type.object"],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": [
                    "variable.other.object.property",
                    "variable.other.property",
                    "support.variable.property",
                ],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": [
                    "entity.name.function.method",
                    "string.unquoted",
                    "meta.object.member",
                ],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": [
                    "variable - meta.import",
                    "constant.other.placeholder",
                    "meta.object-literal.key-meta.object.member",
                ],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": ["keyword.control.flow"],
                "settings": {"foreground": f"{colors.brightMint}c0"},
            },
            {
                "scope": ["keyword.operator.new", "keyword.control.new"],
                "settings": {"foreground": f"{colors.brightMint}"},
            },
            {
                "scope": [
                    "variable.language.this",
                    "storage.modifier.async",
                    "storage.modifier",
                    "variable.language.super",
                ],
                "settings": {"foreground": f"{colors.brightMint}"},
            },
            {
                "scope": [
                    "support.class.error",
                    "keyword.control.trycatch",
                    "keyword.operator.expression.delete",
                    "keyword.operator.expression.void",
                    "keyword.operator.void",
                    "keyword.operator.delete",
                    "constant.language.null",
                    "constant.language.boolean.false",
                    "constant.language.undefined",
                ],
                "settings": {"foreground": f"{colors.hotRed}"},
            },
            {
                "scope": [
                    "variable.parameter",
                    "variable.other.readwrite.js",
                    "meta.definition.variable variable.other.constant",
                    "meta.definition.variable variable.other.readwrite",
                ],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": ["constant.other.color"],
                "settings": {"foreground": f"{colors.white}"},
            },
            {
                "scope": ["invalid", "invalid.illegal"],
                "settings": {"foreground": f"{colors.hotRed}"},
            },
            {
                "scope": ["invalid.deprecated"],
                "settings": {"foreground": f"{colors.hotRed}"},
            },
            {
                "scope": ["keyword.control", "keyword"],
                "settings": {"foreground": f"{colors.gray}"},
            },
            {
                "scope": ["keyword.operator", "storage.type"],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": [
                    "keyword.control.module",
                    "keyword.control.import",
                    "keyword.control.export",
                    "keyword.control.default",
                    "meta.import",
                    "meta.export",
                ],
                "settings": {"foreground": f"{colors.brightMint}"},
            },
            {
                "scope": ["Keyword", "Storage"],
                "settings": {"fontStyle": f"{styles.fontStyle}"},
            },
            {
                "scope": ["keyword-meta.export"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["meta.brace", "punctuation", "keyword.operator.existential"],
                "settings": {"foreground": f"{colors.gray}"},
            },
            {
                "scope": [
                    "constant.other.color",
                    "meta.tag",
                    "punctuation.definition.tag",
                    "punctuation.separator.inheritance.php",
                    "punctuation.definition.tag.html",
                    "punctuation.section.embedded",
                    "keyword.other.template",
                    "keyword.other.substitution",
                    "meta.objectliteral",
                ],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": [
                    "punctuation.definition.tag.begin.html",
                    "punctuation.definition.tag.end.html",
                ],
                "settings": {"foreground": f"{colors.gray}"},
            },
            {
                "scope": ["support.class.component"],
                "settings": {"foreground": f"{colors.brightMint}"},
            },
            {
                "scope": [
                    "entity.name.tag",
                    "entity.name.tag",
                    "meta.tag.sgml",
                    "markup.deleted.git_gutter",
                ],
                "settings": {"foreground": f"{colors.brightMint}"},
            },
            {
                "name": "Function Call",
                "scope": "variable.function, source meta.function-call entity.name.function, source meta.function-call entity.name.function, source meta.method-call entity.name.function, meta.class meta.group.braces.curly meta.function-call variable.function, meta.class meta.field.declaration meta.function-call entity.name.function, variable.function.constructor, meta.block meta.var.expr meta.function-call entity.name.function, support.function.console, meta.function-call support.function, meta.property.class variable.other.class, punctuation.definition.entity.css",
                "settings": {"foreground": f"{colors.offWhite}d0"},
            },
            {
                "name": "Function/Class Name",
                "scope": "entity.name.function, meta.class entity.name.class, meta.class entity.name.type.class, meta.class meta.function-call variable.function, keyword.other.important",
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["source.cpp meta.block variable.other"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["support.other.variable", "string.other.link"],
                "settings": {"foreground": f"{colors.brightMint}"},
            },
            {
                "scope": [
                    "constant.numeric",
                    "support.constant",
                    "constant.character",
                    "constant.escape",
                    "keyword.other.unit",
                    "keyword.other",
                    "string",
                    "constant.language",
                    "constant.other.symbol",
                    "constant.other.key",
                    "markup.heading",
                    "markup.inserted.git_gutter",
                    "meta.group.braces.curly constant.other.object.key.js string.unquoted.label.js",
                ],
                "settings": {"foreground": f"{colors.brightMint}"},
            },
            {
                "scope": ["text.html.derivative"],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": ["entity.other.inherited-class"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["meta.type.declaration"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["entity.name.type.alias"],
                "settings": {"foreground": f"{colors.gray}"},
            },
            {
                "scope": ["keyword.control.as", "entity.name.type", "support.type"],
                "settings": {"foreground": f"{colors.gray}C0"},
            },
            {
                "scope": [
                    "entity.name",
                    "support.orther.namespace.use.php",
                    "meta.use.php",
                    "support.other.namespace.php",
                    "markup.changed.git_gutter",
                    "support.type.sys-types",
                ],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": [
                    "support.class",
                    "support.constant",
                    "variable.other.constant.object",
                ],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": [
                    "source.css support.type.property-name",
                    "source.sass support.type.property-name",
                    "source.scss support.type.property-name",
                    "source.less support.type.property-name",
                    "source.stylus support.type.property-name",
                    "source.postcss support.type.property-name",
                ],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": [
                    "entity.name.module.js",
                    "variable.import.parameter.js",
                    "variable.other.class.js",
                ],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": ["variable.language"],
                "settings": {
                    "foreground": f"{colors.lightBlue}",
                    "fontStyle": f"{styles.fontStyle}",
                },
            },
            {
                "scope": ["entity.name.method.js"],
                "settings": {
                    "foreground": f"{colors.desaturatedBlue}",
                    "fontStyle": f"{styles.fontStyle}",
                },
            },
            {
                "scope": [
                    "meta.class-method.js entity.name.function.js",
                    "variable.function.constructor",
                ],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": ["entity.other.attribute-name"],
                "settings": {
                    "foreground": f"{colors.desaturatedBlue}",
                    "fontStyle": f"{styles.fontStyle}",
                },
            },
            {
                "scope": [
                    "text.html.basic entity.other.attribute-name.html",
                    "text.html.basic entity.other.attribute-name",
                ],
                "settings": {
                    "foreground": f"{colors.lowerMint}",
                    "fontStyle": f"{styles.fontStyle}",
                },
            },
            {
                "scope": ["entity.other.attribute-name.class"],
                "settings": {"foreground": f"{colors.lowerMint}"},
            },
            {
                "scope": ["source.sass keyword.control"],
                "settings": {"foreground": f"{colors.bluishGreen}"},
            },
            {
                "scope": ["markup.inserted"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["markup.deleted"],
                "settings": {"foreground": f"{colors.bluishGray}"},
            },
            {
                "scope": ["markup.changed"],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": ["string.regexp"],
                "settings": {"foreground": f"{colors.lowerMint}"},
            },
            {
                "scope": ["constant.character.escape"],
                "settings": {"foreground": f"{colors.lowerMint}"},
            },
            {
                "scope": ["*url*", "*link*", "*uri*"],
                "settings": {
                    "foreground": f"{colors.lightBlue}",
                    "fontStyle": "underline",
                },
            },
            {
                "scope": [
                    "tag.decorator.js entity.name.tag.js",
                    "tag.decorator.js punctuation.definition.tag.js",
                ],
                "settings": {
                    "foreground": f"{colors.bluishGreen}",
                    "fontStyle": f"{styles.fontStyle}",
                },
            },
            {
                "scope": [
                    "source.js constant.other.object.key.js string.unquoted.label.js"
                ],
                "settings": {
                    "foreground": f"{colors.lowerMint}",
                    "fontStyle": f"{styles.fontStyle}",
                },
            },
            {
                "scope": [
                    "source.json meta.structure.dictionary.json support.type.property-name.json"
                ],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": [
                    "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json"
                ],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": [
                    "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json"
                ],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": [
                    "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json"
                ],
                "settings": {"foreground": f"{colors.bluishGrayBrighter}"},
            },
            {
                "scope": [
                    "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json"
                ],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": [
                    "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json"
                ],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": [
                    "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json"
                ],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": [
                    "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json"
                ],
                "settings": {"foreground": f"{colors.bluishGrayBrighter}"},
            },
            {
                "scope": [
                    "source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json"
                ],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": [
                    "text.html.markdown",
                    "punctuation.definition.list_item.markdown",
                ],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": ["text.html.markdown markup.inline.raw.markdown"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": [
                    "text.html.markdown markup.inline.raw.markdown punctuation.definition.raw.markdown"
                ],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": [
                    "markdown.heading",
                    "markup.heading | markup.heading entity.name",
                    "markup.heading.markdown punctuation.definition.heading.markdown",
                ],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": ["markup.italic"],
                "settings": {
                    "foreground": f"{colors.bluishGrayBrighter}",
                    "fontStyle": f"{styles.fontStyle}",
                },
            },
            {
                "scope": ["markup.bold", "markup.bold string"],
                "settings": {
                    "foreground": f"{colors.bluishGrayBrighter}",
                    "fontStyle": "bold",
                },
            },
            {
                "scope": [
                    "markup.bold markup.italic",
                    "markup.italic markup.bold",
                    "markup.quote markup.bold",
                    "markup.bold markup.italic string",
                    "markup.italic markup.bold string",
                    "markup.quote markup.bold string",
                ],
                "settings": {
                    "foreground": f"{colors.bluishGrayBrighter}",
                    "fontStyle": "bold",
                },
            },
            {
                "scope": ["markup.underline"],
                "settings": {
                    "foreground": f"{colors.bluishGrayBrighter}",
                    "fontStyle": "underline",
                },
            },
            {
                "scope": ["markup.strike"],
                "settings": {"fontStyle": f"{styles.fontStyle}"},
            },
            {
                "scope": ["markup.quote punctuation.definition.blockquote.markdown"],
                "settings": {"foreground": f"{colors.brightMint}"},
            },
            {
                "scope": ["markup.quote"],
                "settings": {"fontStyle": f"{styles.fontStyle}"},
            },
            {
                "scope": ["string.other.link.title.markdown"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["string.other.link.description.title.markdown"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["constant.other.reference.link.markdown"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["markup.raw.block"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["markup.raw.block.fenced.markdown"],
                "settings": {"foreground": f"{colors.bluishGray}50"},
            },
            {
                "scope": ["punctuation.definition.fenced.markdown"],
                "settings": {"foreground": f"{colors.bluishGray}50"},
            },
            {
                "scope": [
                    "markup.raw.block.fenced.markdown",
                    "variable.language.fenced.markdown",
                    "punctuation.section.class.end",
                ],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": ["variable.language.fenced.markdown"],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": ["meta.separator"],
                "settings": {
                    "foreground": f"{colors.bluishGrayBrighter}",
                    "fontStyle": "bold",
                },
            },
            {
                "scope": ["markup.table"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": "token.info-token",
                "settings": {"foreground": f"{colors.lowerBlue}"},
            },
            {
                "scope": "token.warn-token",
                "settings": {"foreground": f"{colors.brightYellow}"},
            },
            {
                "scope": "token.error-token",
                "settings": {"foreground": f"{colors.hotRed}"},
            },
            {
                "scope": "token.debug-token",
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": [
                    "entity.name.section.markdown",
                    "markup.heading.setext.1.markdown",
                    "markup.heading.setext.2.markdown",
                ],
                "settings": {"foreground": f"{colors.offWhite}", "fontStyle": "bold"},
            },
            {
                "scope": "meta.paragraph.markdown",
                "settings": {"foreground": f"{colors.offWhite}d0"},
            },
            {
                "scope": [
                    "punctuation.definition.from-file.diff",
                    "meta.diff.header.from-file",
                ],
                "settings": {"foreground": f"{colors.bluishGray}"},
            },
            {
                "scope": "markup.inline.raw.string.markdown",
                "settings": {"foreground": f"{colors.bluishGrayBrighter}"},
            },
            {
                "scope": "meta.separator.markdown",
                "settings": {"foreground": f"{colors.darkerGray}"},
            },
            {"scope": "markup.bold.markdown", "settings": {"fontStyle": "bold"}},
            {
                "scope": "markup.italic.markdown",
                "settings": {"fontStyle": f"{styles.fontStyle}"},
            },
            {
                "scope": [
                    "beginning.punctuation.definition.list.markdown",
                    "punctuation.definition.list.begin.markdown",
                    "markup.list.unnumbered.markdown",
                ],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": [
                    "string.other.link.description.title.markdown punctuation.definition.string.markdown",
                    "meta.link.inline.markdown string.other.link.description.title.markdown",
                    "string.other.link.description.title.markdown punctuation.definition.string.begin.markdown",
                    "string.other.link.description.title.markdown punctuation.definition.string.end.markdown",
                    "meta.image.inline.markdown string.other.link.description.title.markdown",
                ],
                "settings": {"foreground": f"{colors.lightBlue}", "fontStyle": ""},
            },
            {
                "scope": [
                    "meta.link.inline.markdown string.other.link.title.markdown",
                    "meta.link.reference.markdown string.other.link.title.markdown",
                    "meta.link.reference.def.markdown markup.underline.link.markdown",
                ],
                "settings": {
                    "foreground": f"{colors.lightBlue}",
                    "fontStyle": "underline",
                },
            },
            {
                "scope": [
                    "markup.underline.link.markdown",
                    "string.other.link.description.title.markdown",
                ],
                "settings": {"foreground": f"{colors.brightMint}"},
            },
            {
                "scope": ["fenced_code.block.language", "markup.inline.raw.markdown"],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": [
                    "punctuation.definition.markdown",
                    "punctuation.definition.raw.markdown",
                    "punctuation.definition.heading.markdown",
                    "punctuation.definition.bold.markdown",
                    "punctuation.definition.italic.markdown",
                ],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": ["source.ignore", "log.error", "log.exception"],
                "settings": {"foreground": f"{colors.hotRed}"},
            },
            {"scope": ["log.verbose"], "settings": {"foreground": f"{colors.gray}"}},
            {"scope": ["source.python"], "settings": {"foreground": "#e4f0fbcc"}},
            # For Python (new)
            {
                "scope": ["entity.name.function.python"],
                "settings": {"foreground": "#7AA2F7"},
            },
            {
                "scope": [
                    "comment.line.number-sign.python",
                    "string.quoted.docstring.multi.python",
                ],
                "settings": {"foreground": f"{colors.darkerGray}B0"},
            },
            {
                "scope": [
                    "string",
                    "string.quoted",
                    "string.quoted.single.python",
                    "string.quoted.multi.python",
                    "string.interpolated.python",
                    "string.quoted.docstring.raw.multi.python",
                ],
                "settings": {"foreground": "#5de4a0"},
            },
            {
                "scope": ["constant.other.caps.python"],
                "settings": {"foreground": f"{colors.hotRed}"},
            },
            {
                "scope": [
                    "constant.language.python",
                    "constant.numeric.float.python",
                    "constant.numeric.dec.python",
                ],
                "settings": {"foreground": f"{colors.purple}"},
            },
            {
                "scope": [
                    "string.regexp.quoted.single.python",
                    "string.quoted.raw.single.python",
                ],
                "settings": {"foreground": "#5FB3A1"},
            },
            {
                "scope": [
                    "variable.language.special.self.python",
                    "variable.language.special.cls.python",
                ],
                "settings": {"foreground": "#6f98e4"},
            },
            {
                "scope": [
                    "meta.function-call.generic.python",
                ],
                "settings": {"foreground": "#69b9ff"},
            },
            {
                "scope": [
                    "support.type.python",
                    "support.function.magic.python",
                    "support.function.builtin.python",
                    "support.type.exception.python",
                ],
                "settings": {"foreground": "#4ddaf3"},
            },
            {
                "scope": [
                    "variable.parameter.function.language.special.self.python",
                    "variable.parameter.function.language.special.cls.python",
                    "variable.parameter.function.language.python",
                    "variable.parameter.function-call.python",
                ],
                "settings": {"foreground": "#ebd096"},
            },
            # For C/C++ and headers (new) — mirror the Python palette.
            # Scoped under source.c / source.cpp so only C/C++/headers are affected.
            {
                "scope": ["source.c", "source.cpp", "source.cuda-cpp"],
                "settings": {"foreground": "#e4f0fbcc"},
            },
            {
                "scope": [
                    "source.c comment",
                    "source.cpp comment",
                    "source.cuda-cpp comment",
                ],
                "settings": {
                    "foreground": f"{colors.darkerGray}B0",
                    "fontStyle": f"{styles.fontStyle}",
                },
            },
            {
                "scope": [
                    "source.c string.quoted.double",
                    "source.cpp string.quoted.double",
                    "source.cuda-cpp string.quoted.double",
                    "source.c string.quoted.single",
                    "source.cpp string.quoted.single",
                    "source.cuda-cpp string.quoted.single",
                ],
                "settings": {"foreground": "#5de4a0"},
            },
            {
                "scope": [
                    "source.c string.quoted.other.lt-gt.include",
                    "source.cpp string.quoted.other.lt-gt.include",
                    "source.cuda-cpp string.quoted.other.lt-gt.include",
                    "source.c string.quoted.double.include",
                    "source.cpp string.quoted.double.include",
                    "source.cuda-cpp string.quoted.double.include",
                ],
                "settings": {"foreground": "#5FB3A1"},
            },
            {
                "scope": [
                    "source.c constant.numeric",
                    "source.cpp constant.numeric",
                    "source.cuda-cpp constant.numeric",
                    "source.c constant.language",
                    "source.cpp constant.language",
                    "source.cuda-cpp constant.language",
                ],
                "settings": {"foreground": f"{colors.purple}"},
            },
            {
                "scope": [
                    "source.c storage.type",
                    "source.cpp storage.type",
                    "source.cuda-cpp storage.type",
                ],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": [
                    "source.c storage.type.built-in",
                    "source.cpp storage.type.built-in",
                    "source.cuda-cpp storage.type.built-in",
                    "source.c storage.type.primitive",
                    "source.cpp storage.type.primitive",
                    "source.cuda-cpp storage.type.primitive",
                    "source.c support.type",
                    "source.cpp support.type",
                    "source.cuda-cpp support.type",
                ],
                "settings": {"foreground": "#4ddaf3"},
            },
            {
                "scope": [
                    "source.c storage.modifier",
                    "source.cpp storage.modifier",
                    "source.cuda-cpp storage.modifier",
                ],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": [
                    "source.c keyword.operator",
                    "source.cpp keyword.operator",
                    "source.cuda-cpp keyword.operator",
                ],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": [
                    "source.c keyword.control",
                    "source.cpp keyword.control",
                    "source.cuda-cpp keyword.control",
                ],
                "settings": {"foreground": f"{colors.brightMint}c0"},
            },
            {
                "scope": [
                    "source.c keyword.control.directive",
                    "source.cpp keyword.control.directive",
                    "source.cuda-cpp keyword.control.directive",
                    "source.c punctuation.definition.directive",
                    "source.cpp punctuation.definition.directive",
                    "source.cuda-cpp punctuation.definition.directive",
                ],
                "settings": {"foreground": f"{colors.brightMint}"},
            },
            {
                "scope": [
                    "source.c entity.name.function",
                    "source.cpp entity.name.function",
                    "source.cuda-cpp entity.name.function",
                    "source.c entity.name.function.call",
                    "source.cpp entity.name.function.call",
                    "source.cuda-cpp entity.name.function.call",
                    "source.c entity.name.function.member",
                    "source.cpp entity.name.function.member",
                    "source.cuda-cpp entity.name.function.member",
                ],
                "settings": {"foreground": "#69b9ff"},
            },
            {
                "scope": [
                    "source.c entity.name.function.definition",
                    "source.cpp entity.name.function.definition",
                    "source.cuda-cpp entity.name.function.definition",
                ],
                "settings": {"foreground": "#7AA2F7"},
            },
            {
                "scope": [
                    "source.c entity.name.function.preprocessor",
                    "source.cpp entity.name.function.preprocessor",
                    "source.cuda-cpp entity.name.function.preprocessor",
                ],
                "settings": {"foreground": f"{colors.hotRed}"},
            },
            {
                "scope": [
                    "source.c entity.name.type",
                    "source.cpp entity.name.type",
                    "source.cuda-cpp entity.name.type",
                    "source.cpp entity.name.scope-resolution.type",
                    "source.cuda-cpp entity.name.scope-resolution.type",
                ],
                "settings": {"foreground": f"{colors.lightBlue}"},
            },
            {
                "scope": [
                    "source.cpp entity.name.namespace",
                    "source.cuda-cpp entity.name.namespace",
                    "source.cpp entity.name.scope-resolution",
                    "source.cuda-cpp entity.name.scope-resolution",
                ],
                "settings": {"foreground": f"{colors.desaturatedBlue}"},
            },
            {
                "scope": [
                    "source.c variable.parameter",
                    "source.cpp variable.parameter",
                    "source.cuda-cpp variable.parameter",
                ],
                "settings": {"foreground": "#ebd096"},
            },
            {
                "scope": [
                    "source.c variable.other.property",
                    "source.cpp variable.other.property",
                    "source.cuda-cpp variable.other.property",
                ],
                "settings": {"foreground": f"{colors.offWhite}"},
            },
            {
                "scope": [
                    "source.c variable.other.enummember",
                    "source.cpp variable.other.enummember",
                    "source.cuda-cpp variable.other.enummember",
                ],
                "settings": {"foreground": f"{colors.purple}"},
            },
            {
                "scope": [
                    "source.cpp variable.language.this",
                    "source.cuda-cpp variable.language.this",
                ],
                "settings": {"foreground": "#6f98e4"},
            },
        ],
    }
